### ISSUE TITLE
Include in Experiment parameter_secret_values: section to don't expose values in logs

### ISSUE THREAD

**Issue by netonjm** [microsoft/lst-bench#132]
Sometimes we could need to define a property as a token value and for security reasons we don't want to expose this in logs on exceptions.

<img width="550" alt="CleanShot 2023-09-26 at 12 47 10@2x" src="https://github.com/microsoft/lst-bench/assets/1587480/e659dd4e-7fe9-4597-83b9-d21abbe8c882">

PD: Or any other solution will be fine :-)

**Comment by anjagruenheid** [comment]
After discussing this issue with Jesus, we decided to use a solution that allows users to specify which metadata should be omitted from the log.
