### ISSUE TITLE
[Proposal]Define group execution in task_library

### ISSUE THREAD

**Issue by netonjm** [microsoft/lst-bench#133]
I would be interested in executing different tasks defined in the task library multiple times. 

<img width="533" alt="CleanShot 2023-09-26 at 13 53 42@2x" src="https://github.com/microsoft/lst-bench/assets/1587480/c8891245-bdbe-4233-a18d-883abd082f6d">

To improve readability we could merge both tasks into a group: **single_user_data_maintenance**
<img width="542" alt="CleanShot 2023-09-26 at 13 50 31@2x" src="https://github.com/microsoft/lst-bench/assets/1587480/ed604a55-e032-45ae-bfc1-2f20df06c25a">

The problem of this approach is that the **single_user** and **data_maintenance_delta** are heavy execution tasks and any change in order or files will need to be reflected into single_user_data_maintenance making more complex maintenance.

My proposal is add definition in task_library to tasks groups of "templates" instead of "files"

<img width="951" alt="CleanShot 2023-09-26 at 14 00 51@2x" src="https://github.com/microsoft/lst-bench/assets/1587480/5457b190-a130-4bdc-9a54-5d0c3c2cd81f">

This will associate the already defined tasks to this group and execute in order.

-------

Another approach maybe it could be create template_group node: 

<img width="689" alt="CleanShot 2023-09-26 at 14 16 07@2x" src="https://github.com/microsoft/lst-bench/assets/1587480/5d459a3d-f981-4384-980f-d70e8e0fb820">

<img width="995" alt="CleanShot 2023-09-26 at 14 16 32@2x" src="https://github.com/microsoft/lst-bench/assets/1587480/7e7e893f-180c-4b2f-b186-4d97e07fcc4f">

**Comment by jcamachor** [comment]
Thanks for creating this issue and describing these two proposals, @netonjm . I think both options are reasonable. However, I'd argue that the latter proposal is more readable, since it makes the template group declaration and usage explicit (we can envision support for template groups being in a different `yml` file in the future and thus being reused across template files). @anjagruenheid , WDYT? Any disadvantages you can think of if we go with the second proposal?

**Comment by anjagruenheid** [comment]
The second proposal looks fine to me. We've been talking about simplifying the configs (for example by duplicating a task which is pending in another PR), so this would be another step in that direction for repetitive workloads.
