### ISSUE TITLE
Support using environment variables in config files

### ISSUE THREAD

**Issue by jcamachor** [microsoft/lst-bench#15]
For instance, it would make it easier to replace scripts paths without having to rewrite the config files themselves, thus making config reutilization easier.

**Comment by akshaywakhare** [comment]
Hi, I would like to give this a try.

**Comment by jcamachor** [comment]
Thanks @akshaywakhare ! Looking forward to your contribution, let us know if you have any questions.

**Comment by poojanilangekar** [comment]
Hi, @akshaywakhare are you working on this? If not, I'd be happy to take it up!
