### ISSUE TITLE
Support for the Snowflake Cloud Data Platform

### ISSUE THREAD

**Issue by agr17** [microsoft/lst-bench#265]
# Support for the Snowflake Cloud Data Platform

## Introduction

Hello everyone! In our project, called CLADE, we are analysing and comparing the features of current **data lakehouse** platforms, specifically using **Databricks** and **Snowflake**. Databricks uses Delta as its default table format and Snowflake has recently added support for [Iceberg Tables](https://docs.snowflake.com/en/user-guide/tables-iceberg).

While researching these data formats we discovered LST-Bench, and wanted to use it to measure the efficiency of Delta in Databricks and Iceberg in Snowflake. For the latter platform we need to add specific SQL queries and yaml files in the `run` folder. We are pleased to offer our support for this project by providing support for Snowflake.

## New run configuration

We suggest a new run folder for Snowflake with its own `config` folder containing the sample yaml files and a `scripts` folder containing the necessary sql statements. For the connection to Snowflake it is as simple as adding the corresponding [JDBC Driver](https://docs.snowflake.com/en/developer-guide/jdbc/jdbc) to `pom.xml`.

Scripts can have two build options. One to use the Snowflake default tables and the other one for the new Iceberg tables. The other tasks will be adapted to Snowflake syntax, for example with the use of Stages for data loading.

## Limitations

It is not possible to run the **Optimise task** on Snowflake Managed Iceberg tables. The REFRESH function is only available for externally managed tables, for example in AWS Glue (see [documentation](https://docs.snowflake.com/en/sql-reference/sql/alter-iceberg-table)). For Snowflake Managed Iceberg Tables, the metadata refresh is coordinated internally by Snowflake. If you try to use Refresh on it, the next error is displayed:

`ALTER command failed. The provided table must be an Iceberg table with an external catalog integration to perform the command ICEBERG_TABLE_REFRESH. The type of table ICEBERG_TABLE is MANAGED`

Therefore, we can only run the longevity, concurrency and time travel workloads. In the case of concurrency, the Optimise functions can be replaced by Data Mainteance functions.

---

Finally, just remember that we are happy to develop this support for Snowflake following the previous approach and your feedback, which is welcome.

**Comment by jcamachor** [comment]
@agr17 , this looks like a great proposal, please let us know if you hit any blockers. Looking forward to your contribution!
